// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PutRequest struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutReply struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutReply) Reset()         { *m = PutReply{} }
func (m *PutReply) String() string { return proto.CompactTextString(m) }
func (*PutReply) ProtoMessage()    {}
func (*PutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *PutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutReply.Unmarshal(m, b)
}
func (m *PutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutReply.Marshal(b, m, deterministic)
}
func (m *PutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutReply.Merge(m, src)
}
func (m *PutReply) XXX_Size() int {
	return xxx_messageInfo_PutReply.Size(m)
}
func (m *PutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PutReply.DiscardUnknown(m)
}

var xxx_messageInfo_PutReply proto.InternalMessageInfo

func (m *PutReply) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SubscribeRequest struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	StartingOffset       uint64   `protobuf:"varint,2,opt,name=starting_offset,json=startingOffset,proto3" json:"starting_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *SubscribeRequest) GetStartingOffset() uint64 {
	if m != nil {
		return m.StartingOffset
	}
	return 0
}

type SubscribeReply struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeReply) Reset()         { *m = SubscribeReply{} }
func (m *SubscribeReply) String() string { return proto.CompactTextString(m) }
func (*SubscribeReply) ProtoMessage()    {}
func (*SubscribeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *SubscribeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeReply.Unmarshal(m, b)
}
func (m *SubscribeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeReply.Marshal(b, m, deterministic)
}
func (m *SubscribeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeReply.Merge(m, src)
}
func (m *SubscribeReply) XXX_Size() int {
	return xxx_messageInfo_SubscribeReply.Size(m)
}
func (m *SubscribeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeReply proto.InternalMessageInfo

func (m *SubscribeReply) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SubscribeReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SubscribeReply) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "service.PutRequest")
	proto.RegisterType((*PutReply)(nil), "service.PutReply")
	proto.RegisterType((*SubscribeRequest)(nil), "service.SubscribeRequest")
	proto.RegisterType((*SubscribeReply)(nil), "service.SubscribeReply")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x4e, 0xc3, 0x30,
	0x0c, 0x87, 0x49, 0x3b, 0x06, 0x58, 0x63, 0x0c, 0x83, 0xa0, 0xec, 0x84, 0x72, 0x81, 0xd3, 0x40,
	0xf0, 0x08, 0x48, 0x88, 0xd3, 0x28, 0xdd, 0x03, 0xa0, 0xa6, 0x64, 0xa8, 0x62, 0x22, 0x21, 0x71,
	0x90, 0x7a, 0xe7, 0xc1, 0xd1, 0xbc, 0x6c, 0x2b, 0x7f, 0xb4, 0x9b, 0xfd, 0x4b, 0xf4, 0xf9, 0x8b,
	0x03, 0xfb, 0x5e, 0xbb, 0xcf, 0xba, 0xd2, 0x23, 0xeb, 0x0c, 0x19, 0xdc, 0x89, 0xad, 0x7c, 0x00,
	0xc8, 0x03, 0x15, 0xfa, 0x23, 0x68, 0x4f, 0x78, 0x0c, 0xdb, 0x64, 0x6c, 0x5d, 0x65, 0xe2, 0x5c,
	0x5c, 0xf6, 0x8a, 0x45, 0x83, 0x03, 0x48, 0xdf, 0x74, 0x93, 0x25, 0x9c, 0xcd, 0x4b, 0x44, 0xe8,
	0xbc, 0x94, 0x54, 0x66, 0x29, 0x47, 0x5c, 0x4b, 0x09, 0xbb, 0x4c, 0xb2, 0xb3, 0x06, 0x4f, 0xa0,
	0x6b, 0xa6, 0x53, 0xaf, 0x89, 0x41, 0x9d, 0x22, 0x76, 0xf2, 0x09, 0x06, 0x93, 0xa0, 0x7c, 0xe5,
	0x6a, 0xa5, 0x37, 0xcf, 0xbc, 0x80, 0x03, 0x4f, 0xa5, 0xa3, 0xfa, 0xfd, 0xf5, 0x39, 0xa2, 0x12,
	0x46, 0xf5, 0x97, 0xf1, 0xe3, 0x02, 0x39, 0x86, 0x7e, 0x0b, 0x39, 0x1f, 0x1e, 0x75, 0xc5, 0x5f,
	0xdd, 0x64, 0xad, 0xdb, 0x52, 0x4c, 0xdb, 0x8a, 0x37, 0x5f, 0x02, 0x7a, 0x63, 0x73, 0x1f, 0xbc,
	0xcf, 0x83, 0x9a, 0x04, 0x85, 0x57, 0x90, 0xe6, 0x81, 0xf0, 0x68, 0xb4, 0xdc, 0xe0, 0x7a, 0x5f,
	0xc3, 0xc3, 0x9f, 0xa1, 0x9d, 0x35, 0x72, 0x0b, 0xef, 0x60, 0x6f, 0x65, 0x84, 0x67, 0xab, 0x1b,
	0xbf, 0x1f, 0x3e, 0x3c, 0xfd, 0xef, 0x88, 0x11, 0xd7, 0x42, 0x75, 0xf9, 0x9f, 0x6e, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xf5, 0xa6, 0xd8, 0x13, 0xb8, 0x01, 0x00, 0x00,
}
